project:
  type: website
  output-dir: docs

website:
  back-to-top-navigation: true
  navbar:
    left:
      - href: Home.qmd
        text: Home
      - text: Redesign 1
        href: Case_1.qmd
      - text: Redesign 2
        href: Case_2.qmd
      - text: Codes
        href: Code.qmd
      - text: Video
        href: Video.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

